apiVersion: batch/v1
kind: Job
metadata:
  name: job-guestbook-123
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: job-guestbook
    spec:
      containers:
        - name: job-guestbook
          image: "docker.io/library/hello-world@sha256:54e66cc1dd1fcb1c3c58bd8017914dbed8701e2d8c74d9262e26bd9cc1642d31"
          imagePullPolicy: Always
          resources:
            limits:
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
      restartPolicy: Never
