apiVersion: batch/v1
kind: Job
metadata:
  name: job-guestbook-{{ randNumeric 10 }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: job-guestbook
    spec:
      containers:
        - name: job-guestbook
          image: "docker.io/library/hello-world@sha256:54e66cc1dd1fcb1c3c58bd8017914dbed8701e2d8c74d9262e26bd9cc1642d31"
          imagePullPolicy: Always
          resources:
            limits:
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
      restartPolicy: Never
