apiVersion: batch/v1
kind: Job
metadata:
  name: job-guestbook-{{ randNumeric 10 }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: job-guestbook
    spec:
      containers:
        - name: job-guestbook
          image: "docker.io/library/hello-world@sha256:2771e37a12b7bcb2902456ecf3f29bf9ee11ec348e66e8eb322d9780ad7fc2df"
          imagePullPolicy: Always
          resources:
            limits:
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
      restartPolicy: Never
