apiVersion: batch/v1
kind: Job
metadata:
  name: job-guestbook-{{ randNumeric 10 }}
  # annotations:
  #   argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: job-guestbook
    spec:
      containers:
        - name: job-guestbook
          image: "docker.io/library/hello-world@sha256:2771e37a12b7bcb2902456ecf3f29bf9ee11ec348e66e8eb322d9780ad7fc2df"
          imagePullPolicy: Always
          resources:
            limits:
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
      restartPolicy: Never
